#!/bin/bash -eu

TMP=/tmp/nsp-view
mkdir -p $TMP

(nsp check --reporter=json > $TMP/nsp.json || exit 0)
cat $TMP/nsp.json | jq '.[] | .advisory + " (cvss: " + (.cvss_score | tostring) + ")"' | sort | uniq | sed 's/"//g'

rm -f $TMP/*

