#!/bin/bash -eu

TMP=/tmp/nsp-view
NSP_JSON=$TMP/nsp.json
NSP_ADVISORIES=$TMP/nsp_advisories.log
mkdir -p $TMP

(nsp check --reporter=json > $NSP_JSON || exit 0)
cat $NSP_JSON | jq '.[] | .advisory + " " + (.cvss_score | tostring)' | sort | uniq | sed 's/"//g' > $NSP_ADVISORIES
while read advisory cvss
do
  echo "$advisory (cvss: $cvss)";
  cat $NSP_JSON | jq ".[] | select(.advisory == \"$advisory\") | .path | join(\" > \")" | sed 's/^/  /'
done < $NSP_ADVISORIES

rm -f $TMP/*
